
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvyldmazpktevdxeaavq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2eWxkbWF6cGt0ZXZkeGVhYXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjU3MTQsImV4cCI6MjA1ODQwMTcxNH0.imdsb6IJfScPYjn1W_NB4B4HJkdx5s9ABgsFaPPKQOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
